title: This is Angelina's Website
author: Huilan (Angelina) You
email: huilan.you@qq.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my page. Are you also a fan of data science like me?! 

# social links
linkedIn_link: https://www.linkedin.com/in/angelina-huilanyou/
github_username:  angelinayhl 

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
